#!/bin/sh

set -e
umask 0002

OPTIONS="--show - --fqdn tls-dns --fqdn tls-client-dns --symlink-base /etc/pki/tls/certs --symlink-suffix .crt --symlink tls-ca --symlink-base /etc/pki/tls/certs --symlink-suffix .crt --symlink tls-client-ca"

if [ "$1" == "--" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

fi


