#!/bin/bash

if [ $# -eq 4 ]; then

  instance="${1}"
  virtualhost="${2}"
  url="${3}"

  #
  # Handle discovery locations
  
  # find /etc/device/services/mail/discovery/ -mindepth 1 -maxdepth 1 -type l
  while read line; do

    if test ! -f "$line/virtualhost.d/listen.d/instance.d/name.txt" -o "${instance}" != "$(head -n 1 $line/virtualhost.d/listen.d/instance.d/name.txt)"; then
      continue;
    fi
    if test ! -f "$line/virtualhost.d/name.txt" -o "${virtualhost}" != "$(head -n 1 $line/virtualhost.d/name.txt)"; then
      continue;
    fi

    echo
    echo "    Mail Discovery:"
    echo "      url: ${url}/autodiscovery/"

  done < <(find /etc/device/services/mail/discovery/ -mindepth 1 -maxdepth 1 -type l)

fi


